### ISSUE TITLE
Returns Error 500 no matter what

### ISSUE THREAD

**Issue by GalaxySH** [tronalddump-io/tronald-app#5]
I'm running a nodejs app, and am using node-fetch to send a request and get the json response from the api. When I request, for example, https://api.tronalddump.io/tag/Hillary%20Clinton in my browser (typing it in) it loads up the page with all the quotes. But when I send the request for https://api.tronalddump.io/tag/Hillary%20Clinton it returns error 500. This happens for all the tags.

**Comment by matchilling** [comment]
Hi @GalaxySH 👋, thanks for getting in touch and reporting the issue. Due to some erroneous request mappings on the tag endpoint for `JSON` and `HAL+JSON` requests you were getting 500 responses.

The issue has been fixed with the latest release.
